<%
#require 'cucumber_in_groups'

common = "--tags ~@wip --strict"

lib = "features/step_definitions features/support"

%>

# 'normal' test runs
default: <%= common %> <%= lib %> features/desktop features/mobile
